name: CI Build

on: [push, pull_request]

jobs:
  build-windows:
    name: Windows build
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Build
      run: make -f fbdump.mak windows
    - name: Create artifact
      uses: actions/upload-artifact@main
      with:
        name: windows-executable
        path: build/fbdump.exe
        overwrite: true
        if-no-files-found: error

