name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    name: Windows build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -f fbdump.mak windows
